baseURL = "https://markussvan.com"
languageCode = "en-us"
title = "Markus Svan"
theme = "github-style"

[params]
	author = "Markus Svan"
	avatar = "/images/avatar.jpg"
	description = "I use Arch btw."
	github = "Maroko1218"
	email = "mail@markussvan.com"
	url = "https://markussvan.com/"
	favicon = "/images/github-mark-white.png"
	location = "Sweden"
	headerIcon = "/images/github-mark-white.png"
	enableGitalk = true
	enableSearch = true

	[[params.links]]
		title = "Work GitHub"
		href = "https://github.com/MS-poji"
		icon = "https://markussvan.com/images/github-mark-white.png"


	[params.gitalk]
		clientID = "Ov23likuqOyU4kZG7uOl"
		clientSecret = "b3d2b131a8aa631a3755bdf52d2b6c25e78697c4"
		repo = "markussvan.com-gitalk"
		owner = "Maroko1218"
		admin = "Maroko1218"
		id = "location.pathname"
		labels = "gitalk"
		perPage = 15
		pagerDirection = "last"
		createIssueManually = true
		distractionFreeMode = false

[outputs]
	home = ["html", "json"]

[outputFormats.json]
	mediaType = "application/json"
	baseName = "index"
	isPlainText = false