baseURL = "https://markussvan.com"
languageCode = "en-us"
title = "Markus Svan"
theme = "github-style"

[params]
	author = "Markus Svan"
	avatar = "/images/avatar.jpg"
	description = "I use Arch btw."
	github = "Maroko1218"
	email = "mail@markussvan.com"
	url = "https://markussvan.com/"
	favicon = "/images/github-mark-white.png"
	location = "Sweden"
	headerIcon = "/images/github-mark-white.png"
	enableSearch = true

	[[params.links]]
		title = "Work GitHub"
		href = "https://github.com/MS-poji"
		icon = "https://markussvan.com/images/github-mark-white.png"


	[params.giscus]
        repo = "Maroko1218/markussvan.com-gitalk"
        repoID = "R_kgDONy9-ag"
        category = "Comments"
        categoryID = "DIC_kwDONy9-as4CnfZX"
        mapping = "og:title"
        strict = "1"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "top"
        lang = "en"
        crossOrigin = "anonymous"


[outputs]
	home = ["html", "json"]

[outputFormats.json]
	mediaType = "application/json"
	baseName = "index"
	isPlainText = false