baseURL = "https://markussvan.com"
languageCode = "en-us"
title = "Markus Svan"
theme = "github-style"
[params]
	author = "Markus Svan"
	avatar = "/images/avatar.jpg"
	description = "I use Arch btw."
	github = "Maroko1218"
	email = "mail@markussvan.com"
	url = "https://markussvan.com/"
	favicon = "/images/github-mark-white.png"
	location = "Sweden"
	headerIcon = "/images/github-mark-white.png"
